name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-on-push-tag:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1.0.0
      with:
        node-version: 12

    - name: Set Release Version
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

    - name: Get Release version
      run: echo $RELEASE_VERSION

    - name: Update Git Identity
      run: git config --global user.name '@vreshch' && git config --global user.email 'vreshch@gmail.com' && git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Reattach HEAD to Head Ref
      run: git checkout "$(echo ${{ github.head_ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
      if: github.head_ref != ''
    - name: Reattach HEAD to Ref
      run: git checkout "$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
      if: github.head_ref == ''
    - name: Remove Tag
      run:  git push --delete origin $RELEASE_VERSION && git tag -d $RELEASE_VERSION

    - name: Checkout to master
      run: git checkout master && git reset --hard

    - name: Install dependencies
      run: npm ci && npm run bootstrap:ci

    - name: Reset to master
      run: git checkout master && git reset --hard

    - name: Verify build
      run: npm run lint & npm run test

    - name: Build
      run: npm run build

    - name: Reset Changes in Lock files
      run: git reset --hard

    - name: Setup npmrc File
      run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

    - name: Publish with Lerna
      run: npm run release -- $RELEASE_VERSION
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update dependencies
      run: npm run update-lock-files && git add **/package-lock.json && git commit --amend --no-edit
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Push To Github
      run: git push --follow-tags
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Github Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          Release Changes
        draft: false
        prerelease: false
